version: "3.7"
services:
  corona:
    build: .
    ports:
      - "8501:8501"
    environment:
      - TZ=Australia/ACT
      - ENV=UAT
    volumes:
      - ./persistent/repos:/app/repos
      - ./persistent/data/processed:/app/data/processed
      - ./persistent/data/outputs:/app/data/outputs
      - ./persistent/data/models:/app/data/models
    restart: unless-stopped
